Develop
DDDimbo/java-filmorate pull request #29
Opened 2022-09-01 17:01 UTC by DDDimbo

2022-09-01 20:07 UTC, ddddemo1984 requested changes

2022-09-01 20:07 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else if ("likes".equals(sortBy)) {
Напрашивается enum со значениями year и likes

2022-09-01 20:07 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            else if (by.contains("director"))
Здесь тоже лучше title и director положить в enum

2022-09-02 08:52 UTC, DDDimbo commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoImpl.java
> +                " GROUP BY f.ID" +
а где можно почитать про подобноее, просто в этом спринте часто вылетала ошибка sql связанная с группировкой и я так и не понял, когда нужно определенные поля группировать и почему

2022-09-02 08:58 UTC, DDDimbo commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
>          if (resFilm != null) {
![image](https://user-images.githubusercontent.com/92802270/188103502-86abea60-2f4b-4a7f-b841-10e837f2a618.png)
просто он у меня подсвечивает setGenre. Так оставить? просто с null он же не отработает, а вернет эту ошибку EmptyResultDataAccessException, а когда не null, то и так все хорошо

2022-09-02 09:02 UTC, DDDimbo commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +        return directorService.get(id);
А где вообще лучше логировать? Я читал, что слишком много логов плохо для производительности. В нашем проекте лучше в контроллерах или сервисах делать их? или даже в хранилище? или везде можно?

2022-09-02 11:30 UTC, DDDimbo commented
А чтобы отправить новое ревью нужно опять два эпрува?

2022-09-02 18:21 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +        return directorService.get(id);
Скорее слишком много логов - слишком много занимаемого места - мало времени жизни логов. Я бы логировал в контроллерах, как точка входа из внешнего мира, т.к. узнав что пришло на вход - сможешь отдебажить это локально/ на тестовом сервере

2022-09-02 18:44 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoImpl.java
> +                " GROUP BY f.ID" +
Почитай как в sql работают функции агрегации. Грубо говоря, в select должны быть либо поля из GROUP BY либо функции агрегации(count, sum и тд). Например здесь, если ты сгруппировал только по f.ID и с этим f.ID будет несколько m.ID, то что БД должна вывести?

2022-09-02 18:47 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
>          if (resFilm != null) {
Странно, у меня не подсвечивает, думаю это баг конкретной идеи

2022-09-02 18:48 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +                "VALUES (?, ?,(SELECT id FROM users WHERE id = ?), (SELECT id  FROM films WHERE id = ?))";
Не поправлено, и это нужно поправить

2022-09-02 18:55 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        } catch (RuntimeException ex) {
Не поправлено, нужно поправить

2022-09-03 11:21 UTC, DDDimbo commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +        return directorService.get(id);
Ок, спасибо

2022-09-05 18:08 UTC, DDDimbo commented
Исправил замечания

2022-09-05 18:09 UTC, DDDimbo commented
Ужасно накосячил, перепутал в тренажере 11 и 12 спринт, подумал, что уже зачли, поэтому так поздно отправляю

2022-09-05 19:33 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "GROUP BY f.id, fg.genre_id\n" +
Не поправлено. Если в запросе есть функция агрегирования такая как COUNT, то все поля в селекте, должны быть в GROUP BY, либо в функция агрегирования

2022-09-05 19:35 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +                "VALUES (?, ?,(SELECT id FROM users WHERE id = ?), (SELECT id  FROM films WHERE id = ?))";
Не поправлено, и это нужно поправить

2022-09-06 14:18 UTC, DDDimbo commented
Разобрался как связан Select и Group By, исправил запросы, некоторые переписал.

2022-09-06 17:28 UTC, ddddemo1984 requested changes

2022-09-06 17:28 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +                "VALUES (?, ?,(SELECT id FROM users WHERE id = ?), (SELECT id  FROM films WHERE id = ?))";
Не поправлено, и это нужно поправить.
В чём сложность убрать эти не нужные селекты, т.е. сделать: 
"INSERT INTO reviews (content, is_positive, user_id, film_id) " +
                "VALUES (?, ?, ?, ?)" ?

2022-09-06 18:49 UTC, DDDimbo commented
А я думал про другое вы писали, сейчас исправлю

2023-02-26 21:48 UTC, merged